### ISSUE TITLE
Cache errors while working with Link header

### ISSUE THREAD

**Issue by jbehrens94** [joakimskoog/AnApiOfIceAndFire#120] opened 2017-06-20 18:19 UTC
I suspect I am encountering an error in the API when I call it: Sometimes it returns a Link header, sometimes it doesn't, which doesn't make sense to me. I do the call from Angular 4, with the custom JSON Accept header included and the right version.

What should I do about this?

**Comment by joakimskoog** [comment] 2017-06-20 19:29
Could you please provide the requests you send and the responses you get so that I can check it out more easily?

**Comment by jbehrens94** [comment] 2017-06-20 19:47
Sure! In what format would you like it?

**Comment by joakimskoog** [comment] 2017-06-20 19:48
Request url+headers and then the response payload + headers would be  great. Either in a comment here or a gist would also be fine.

**Comment by jbehrens94** [comment] 2017-06-20 19:52
By the way, in Postman everything works perfectly fine, I always get the Link Header. When I do it in Angular 4, I don't always receive it, it varies. I suppose it is related to the CORS-settings, which I saw issues about before?

Those are the response headers. Even the browser leaves out the Link Header.
<img width="299" alt="schermafbeelding 2017-06-20 om 21 49 56" src="https://user-images.githubusercontent.com/5713854/27352889-8c0b0306-5602-11e7-95dc-5b1255ec5c55.png">

Those are the headers I send with my request.
<img width="300" alt="schermafbeelding 2017-06-20 om 21 50 05" src="https://user-images.githubusercontent.com/5713854/27352890-8c278d96-5602-11e7-8c60-058a8ab72281.png">

This is the actual URL I'm calling.
<img width="300" alt="schermafbeelding 2017-06-20 om 21 50 17" src="https://user-images.githubusercontent.com/5713854/27352891-8c295f4a-5602-11e7-902f-92c28b6d5ddc.png">

Sorry for the Dutch properties and all, I hope you'll still understand them. :)

**Comment by joakimskoog** [comment] 2017-06-20 19:56
Are you saying that you **never** get the link headers when calling from Angular or that you get them sometimes?

**Comment by jbehrens94** [comment] 2017-06-20 19:57
I'm getting them sometimes in the browser, never in Angular, so I'm sure there's also something wrong in Angular, but the browser should display them correctly all the time right?

**Comment by jbehrens94** [comment] 2017-06-20 19:58
I also tried sending these additional headers:

`headers.append('Access-Control-Expose-Headers', '*');`
Or: `headers.append('Access-Control-Expose-Headers', 'Link');`

**Comment by joakimskoog** [comment] 2017-06-20 19:59
That sounds super weird, I'll check it out either later tonight or tomorrow. Thank you for submitting the issue. 👍

**Comment by jbehrens94** [comment] 2017-06-20 20:00
Thank you so much for hearing me out and I'm looking forward to your response later on. 👍

**Comment by jbehrens94** [comment] 2017-06-21 10:00
Also, is it easy for me to clone the repo and setup the server myself? Is all of the data present in your JSON files?

**Comment by joakimskoog** [comment] 2017-06-21 10:03
It should be easy enough: https://github.com/joakimskoog/AnApiOfIceAndFire/blob/master/CONTRIBUTING.md

Note that I'm going to port the project to .NET Core soon which will enable it to run on both Mac and Linux

**Comment by jbehrens94** [comment] 2017-06-21 10:09
So all data is available in the .Data folder? :)

**Comment by joakimskoog** [comment] 2017-06-21 10:10
That is correct. :)

**Comment by jbehrens94** [comment] 2017-06-21 10:20
I just found out that if I disable caching at all in Safari, it makes the right request every time. So that is part one solved, now the problem why Angular doesn't pick up the right headers. Could that be an issue with CORS?
I included a screenshot with the response I receive.

Apparently, the API should return Allow-Access-Expose-Headers according to [this url](https://stackoverflow.com/questions/40508187/angular2-s-http-post-is-not-returning-headers-in-the-response-of-a-post-method#comment68258543_40508187).

<img width="1440" alt="schermafbeelding 2017-06-21 om 12 19 56" src="https://user-images.githubusercontent.com/5713854/27379564-fbd81cf4-567b-11e7-99c2-859182d5dd63.png">

**Comment by jbehrens94** [comment] 2017-06-21 14:01
@joakimskoog I forked this project and cloned it in VS2017, but it can't build because there are packages missing from NuGet. I tried running `Update-Package` and such, but it doesn't work for me. Could you help me?

**Comment by joakimskoog** [comment] 2017-06-21 14:14
What kind of error message are you getting?

**Comment by jbehrens94** [comment] 2017-06-21 14:17
I checked it out from GitHub, opened it, opened the NuGet Package Manager Console and I run `Update-Package` in the root directory of the repo. `Project "Default" is not found.`

**Comment by jbehrens94** [comment] 2017-06-21 14:32
Did you create the projects in VS2015 or VS2017? Maybe that helps me out :)

**Comment by joakimskoog** [comment] 2017-06-21 15:56
First of all, the command Update-Package requires a project name as an argument (as seen [here](https://docs.microsoft.com/en-us/nuget/consume-packages/reinstalling-and-updating-packages)).

Also the project was built with VS 2015 but that does not matter since VS 2017 can be used to build VS 2015 projects.

**Comment by joakimskoog** [comment] 2017-06-21 16:05
@jbehrens94: I could actually reproduce the error with jquery and it seems that when making CORS you can only access certain headers as seen [here](https://stackoverflow.com/questions/37400091/missing-headers-in-response-for-jquery-request-with-cors).

**Comment by jbehrens94** [comment] 2017-06-21 16:18
I opened it in VS2015, working now! When I run it, however, it doesn't seem to be able to build the database? I changed the connectionString in `AnApiOfIceAndFire/Web.config`, but I read I should run `Update-Database` in the .Data project. I'm not sure how I should set this up, could you help me out on this, or add the Access-Control-Allow-Headers?

**Comment by jbehrens94** [comment] 2017-06-21 16:27
I also see in the C# code (AnApiOfIceAndFire/App_Start/WebApiConfig.cs) that we have this code:

private static void EnableCrossSiteRequests(HttpConfiguration config)
{
    var cors = new EnableCorsAttribute(origins: "*", headers: "*", methods: "GET,HEAD");                 config.EnableCors(cors);
}

That should enable Angular 4 to get all of the headers, right?

**Comment by joakimskoog** [comment] 2017-06-21 16:43
Yeah, that should be enough, hmm...Maybe there's something you have to configure on your end?

**Comment by jbehrens94** [comment] 2017-06-21 16:50
Might be, but it's still strange that your test with jQuery also didn't produce the correct results, right?

**Comment by jbehrens94** [comment] 2017-06-21 16:51
Or should it be a caching issue still, as Safari produces the correct results when caching is disabled?

**Comment by joakimskoog** [comment] 2017-07-11 09:40
Closing this as I rolled out a new version of the project that is completely rebuilt and based on ASP.NET Core. Please open a new issue if the problem persists.

**Closed as completed by joakimskoog** 2017-07-11 09:40 UTC
Labels: bug, wontfix
